---


- name: stop httpd
  service: name=httpd state=stopped

- name: stop mysqld
  service: name=mysqld state=stopped

- name: start mysqld
  service: name=mysqld state=started

- name: restart iptables
  action: service name=iptables state=restarted

- name: Restart server
  shell: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true