---

- include: ol7.yml
  when: ansible_distribution == "OracleLinux" and (ansible_distribution_major_version|int == 7)

- include: rh6.yml
  when: ansible_distribution == "RedHat" and (ansible_distribution_major_version|int == 6)

- include: rh7.yml
  when: ansible_distribution == "RedHat" (ansible_distribution_major_version|int == 7)

# - name: Ensure Aspera User is Present
#   user: name=aspera group=users shell="/bin/aspshell" state=present
#   sudo: yes