---

- include: ol7.yml
  when: ansible_distribution == "OracleLinux" and (ansible_distribution_major_version|int == 7)

- include: rh6.yml
  when: ansible_distribution == "RedHat" and (ansible_distribution_major_version|int == 6)

- include: rh7.yml
  when: ansible_distribution == "RedHat" (ansible_distribution_major_version|int == 7)

- name: Ensure User is Present
  user: name=aspera group=users shell="/bin/bash" state=present
  sudo: yes
  
- copy: src=/Users/boom/Downloads/aspera-common-1.2.14.110759-0.x86_64.rpm dest=/root owner=root group=root mode=0744
  sudo: yes
- copy: src=/Users/boom/Downloads/aspera-console-3.0.2.111237-0.x86_64.rpm dest=/root owner=root group=root mode=0744
  sudo: yes 

- name: Install Aspera Common Components
  yum: name=/root/aspera-common-1.2.14.110759-0.x86_64.rpm state=present
- name: Install Aspera aspera-console
  yum: name=/root/aspera-console-3.0.2.111237-0.x86_64.rpm state=present

- name: Open the correct IPTables ports
  lineinfile: dest=/etc/sysconfig/iptables
              regexp="^-A INPUT -p {{item.protocol}} -m state --state NEW -m {{item.protocol}} --dport {{item.port}} -j ACCEPT$"
              line="-A INPUT -p {{item.protocol}} -m state --state NEW -m {{item.protocol}} --dport {{item.port}} -j ACCEPT"
              insertbefore="^-A INPUT -j REJECT --reject-with icmp-host-prohibited$"            
  with_items:
        - { protocol: tcp, port: 80 }
        - { protocol: tcp, port: 443 }
        - { protocol: tcp, port: 389 }
        - { protocol: tcp, port: 636 }
        - { protocol: tcp, port: 88 }
        - { protocol: tcp, port: 464 }
        - { protocol: tcp, port: 53 }
        - { protocol: tcp, port: 33001 }
        - { protocol: tcp, port: 40001 }
        - { protocol: tcp, port: 4406 }
        - { protocol: tcp, port: 22 }
        - { protocol: udp, port: 88 }
        - { protocol: udp, port: 464 }
        - { protocol: udp, port: 53 }
        - { protocol: udp, port: 123 }
        - { protocol: udp, port: 33001-33010 }
  notify:
        - restart iptables

